name: mangadex_mobile
description: Mobile-based Manga Reader Application built on top of MangaDex API

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.5
  dot_navigation_bar: ^1.0.1+4
  fluro: ^2.0.3
  flutter_svg: ^1.0.3
  line_icons: ^2.0.1
  provider: ^6.0.2
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
